#!/usr/bin/env python3
"""Pure, deterministic GitHub browsing views over immutable Team Hub records."""
import hashlib
import html
import json
import posixpath
import re
import unicodedata

from hub_store import HubError, MAX_TEXT, encoded

START = '<!-- blog-studio:library:start -->'
END = '<!-- blog-studio:library:end -->'
NOTICE = '> Generated by Blog Studio. Edit through Blog Studio; these browsing views are not the source of record.\n'


def safe(value):
    text = ' '.join(str(value).split())
    text = html.escape(text, quote=True)
    for char in '|[]@`*_\\':
        text = text.replace(char, '&#' + str(ord(char)) + ';')
    return text


def slug(value, fallback):
    ascii_text = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore').decode()
    return re.sub(r'[^a-z0-9]+', '-', ascii_text.lower()).strip('-')[:70].rstrip('-') or fallback


def record_path(record, file='record.json'):
    return 'memory/items/' + record['item'] + '/revisions/' + record['revision'] + '/' + file


def link(label, target, page):
    return '[' + safe(label) + '](' + posixpath.relpath(target, posixpath.dirname(page) or '.') + ')'


def owner(record, graph):
    studio = record['data'].get('studio', {})
    if not isinstance(studio, dict):
        studio = {}
    explicit = studio.get('author') or record['data'].get('author')
    if isinstance(explicit, str) and explicit.strip():
        return explicit.strip()
    for dependency in record['dependencies']:
        if dependency.get('role') == 'voice':
            return graph['revisions'][dependency['revision']]['title'] or 'Unassigned'
    return 'Unassigned'


def managed_block(readme):
    if START not in readme and END not in readme:
        return None
    if readme.count(START) != 1 or readme.count(END) != 1 or readme.index(START) > readme.index(END):
        raise HubError('The generated homepage markers were edited. Preserve those edits before rebuilding the blog library.')
    return readme[readme.index(START):readme.index(END) + len(END)]


def render(files, graph):
    rows = []
    for item, heads in sorted(graph['heads'].items()):
        records = [graph['revisions'][revision] for revision in heads]
        if records[0]['kind'] != 'article' or all(r['status'] == 'tombstone' for r in records):
            continue
        records.sort(key=lambda r: (r['created_at'], r['revision']))
        record = records[-1]
        rows.append({'item': item, 'record': record, 'heads': records,
                     'author': owner(record, graph), 'conflict': len(records) > 1})
    # Slugs are normalized for portability. Disambiguate authors with identical
    # ASCII slugs, then article titles using enough stable-ID characters to be unique.
    authors = {}
    for row in rows:
        authors.setdefault(slug(row['author'], 'author'), set()).add(row['author'])
    groups = {}
    for row in rows:
        author_slug = slug(row['author'], 'author')
        if len(authors[author_slug]) > 1:
            author_slug += '-' + hashlib.sha256(row['author'].encode()).hexdigest()[:12]
        row['base'] = 'blogs/' + author_slug + '/' + slug(row['record']['title'], 'untitled')
        groups.setdefault(row['base'], []).append(row)
    reserved = set(groups)
    assigned = set()
    for base, grouped in sorted(groups.items()):
        width = 8
        while len({row['item'][:width] for row in grouped}) != len(grouped):
            width += 1
        for row in sorted(grouped, key=lambda r: r['item']):
            candidate = base + ('-' + row['item'][:width] if len(grouped) > 1 else '')
            counter = 2
            original = candidate
            while candidate in assigned or (len(grouped) > 1 and candidate in reserved):
                candidate = original + '-' + str(counter);counter += 1
            row['folder'] = candidate;assigned.add(candidate)
    rows.sort(key=lambda row: (row['author'].casefold(), row['record']['title'].casefold(), row['item']))
    output = {}
    for row in rows:
        record = row['record'];folder = row['folder'];page = folder + '/README.md'
        data = record['data'].get('studio', {})
        if not isinstance(data, dict):data = {}
        stage = 'conflict — choose a revision in Blog Studio' if row['conflict'] else str(data.get('stage', record['status']))
        row['stage'] = stage
        row['updated'] = max(r['created_at'] for r in row['heads'])
        header = '# ' + safe(record['title']) + '\n\n' + NOTICE + '\n'
        header += '**Author:** ' + safe(row['author']) + '  \n**Stage:** ' + safe(stage) + '  \n**Updated:** ' + safe(row['updated']) + '\n\n'
        header += ' | '.join((link('All blogs', 'blogs/README.md', page), link('Context', folder + '/context.md', page),
                              link('History', folder + '/history.md', page))) + '\n\n'
        if row['conflict']:
            header += '## Competing revisions\n\nNo current draft is selected until the conflict is resolved.\n\n'
            for head in row['heads']:
                header += '- ' + link(head['title'] + ' — ' + head['status'], record_path(head), page) + '\n'
        else:
            header += link('Canonical revision', record_path(record), page) + '\n\n'
            draft = 'artifacts/DRAFT.md' if record['files'].get('artifacts/DRAFT.md', {}).get('media') == 'text' else 'BODY.md'
            body = files[record_path(record, draft)].decode('utf-8')
            if not body.strip():
                for candidate, label in (('artifacts/OUTLINE.md', 'Outline'), ('artifacts/BRIEF.md', 'Brief')):
                    if record['files'].get(candidate, {}).get('media') == 'text':
                        body = '## ' + label + '\n\n' + files[record_path(record, candidate)].decode('utf-8');break
            header += '---\n\n' + (body if body.strip() else 'No draft or outline has been saved yet.\n')
            if record['files'].get('artifacts/OUTLINE.md', {}).get('media') == 'text':
                outline_page = folder + '/outline.md'
                output[outline_page] = (NOTICE + '\n' + link('Blog', page, outline_page) + '\n\n' + files[record_path(record, 'artifacts/OUTLINE.md')].decode('utf-8')).encode()
                header = header.replace('---\n\n', link('Outline', outline_page, page) + '\n\n---\n\n', 1)
        output[page] = header.encode()
        context_page = folder + '/context.md'
        context = '# Selected context\n\n' + NOTICE + '\n' + link('Blog', page, context_page) + '\n\n'
        if row['conflict']:
            context += 'Context differs between competing revisions. Inspect each canonical revision in the history.\n'
        else:
            context += '- Author: ' + safe(row['author']) + '\n- Stage: ' + safe(stage) + '\n'
            context += '- Research: ' + safe(data.get('research_policy', 'unspecified')) + '\n'
            context += '- Stop: ' + safe(data.get('stop_point', 'unspecified')) + '\n\n## Selected sources, voice, and team context\n\n'
            for dependency in record['dependencies']:
                selected = graph['revisions'][dependency['revision']]
                role = dependency.get('role', dependency['kind'])
                context += '- ' + safe(role) + ': ' + link(selected['title'], record_path(selected, 'BODY.md'), context_page) + '\n'
            if not record['dependencies']:context += 'None selected.\n'
            context += '\n## Active article preferences\n\n'
            memory = data.get('memory', {})
            active = [(key, entry) for key, entry in memory.items() if isinstance(entry, dict) and entry.get('status') == 'active'] if isinstance(memory, dict) else []
            context += ''.join('- ' + safe(key) + ': ' + safe(entry.get('text', '')) + '\n' for key, entry in sorted(active)) or 'None.\n'
        output[context_page] = context.encode()
        history_page = folder + '/history.md'
        history = '# Revision history\n\n' + NOTICE + '\n' + link('Blog', page, history_page) + '\n\n'
        history += '| Saved | Title | Status | Content | Details |\n| --- | --- | --- | --- | --- |\n'
        revisions = sorted((r for r in graph['revisions'].values() if r['item'] == row['item']), key=lambda r: (r['created_at'], r['revision']), reverse=True)
        for saved in revisions:
            content = next((name for name in ('artifacts/DRAFT.md', 'artifacts/OUTLINE.md', 'artifacts/BRIEF.md') if saved['files'].get(name, {}).get('media') == 'text'), 'BODY.md')
            history += '| ' + safe(saved['created_at']) + ' | ' + safe(saved['title']) + ' | ' + safe(saved['status']) + ' | ' + link('Read', record_path(saved, content), history_page) + ' | ' + link('Revision', record_path(saved), history_page) + ' |\n'
        output[history_page] = history.encode()
    def index(page):
        result = '## Blog library\n\n' + NOTICE + '\n'
        if not rows:return result + 'No blogs have been shared yet. Save or import a selected article through Blog Studio.\n'
        result += '| Blog | Author | Stage | Updated |\n| --- | --- | --- | --- |\n'
        for row in rows:
            result += '| ' + link(row['record']['title'], row['folder'] + '/README.md', page) + ' | ' + safe(row['author']) + ' | ' + safe(row['stage']) + ' | ' + safe(row['updated']) + ' |\n'
        return result
    output['blogs/README.md'] = ('# Blogs\n\n' + index('blogs/README.md')).encode()
    readme = files.get('README.md', b'').decode('utf-8')
    block = START + '\n' + index('README.md') + END
    previous = managed_block(readme)
    output['README.md'] = (readme.replace(previous, block) if previous else readme.rstrip() + '\n\n' + block + '\n').encode()
    if any(len(content) > MAX_TEXT for content in output.values()):
        raise HubError('A generated library page exceeds the hub text limit; saved work remains queued.')
    return output


def verify(files, graph):
    """Do not silently overwrite edits to generated pages or an unrelated blogs/ tree."""
    actual = {name: body for name, body in files.items() if name.startswith('blogs/')}
    if graph['manifest'].get('browse_schema') != 1:
        if actual or managed_block(files.get('README.md', b'').decode()):
            raise HubError('The blog library destination already contains unmanaged content; it was preserved.')
        return
    expected = render(files, graph)
    if (actual != {name: body for name, body in expected.items() if name.startswith('blogs/')}
            or managed_block(files.get('README.md', b'').decode()) != managed_block(expected['README.md'].decode())):
        raise HubError('Generated blog pages were edited or removed. Preserve/import those edits and restore the generated pages before syncing; queued work is retained.')


def changes(files, graph):
    output = render(files, graph)
    manifest = dict(graph['manifest'], browse_schema=1, minimum_runtime='1.3.0')
    output['hub.json'] = encoded(manifest)
    return {**{name: None for name in files if name.startswith('blogs/') and name not in output},
            **{name: body for name, body in output.items() if files.get(name) != body}}
